$SearchTerm = "Baritone | cabaletta | Jigsaw | LiquidBounce | Wurst | GishCode | Inertia | Impact | rename_me_please.dll | Future | RusherHack | Pyro | Zamorozka | Konas | WintWare | Nursultan | Norules | Akrien | Sigma | DeadCode | Eternity | WEXSIDE | Rich | RichPremium | EdItMe.dll | mc100.dll | Matix | R3D | Celestial | Wild | Destroy | ArchWare | NightMare | BoberWare | FLauncher | ExLoader | celka | CelestialBaritone | cabaletta | Jigsaw | LiquidBounce | Wurst | GishCode | Inertia | Impact | rename_me_please.dll | Future | RusherHack | Pyro | Zamorozka | Konas | WintWare | Nursultan | Norules | Akrien | Sigma | DeadCode | Eternity | WEXSIDE | Rich | RichPremium | EdItMe.dll | mc100.dll | Matix | R3D | Celestial | Wild | Destroy | ArchWare |NightMare | BoberWare | FLauncher | ExLoader | celka | Celestial | xray | x-ray | itemscroller | doomsday | Freecam | MouseTweaks | akrien | AutoChest | ChestStealer | BetterClicker | cortex | troxil | .akr | .wex | NoRender | AkrienAntiLeek | Vape | pivo | dauntiblyat.dll | meteor | ares | aristois | bleachhack | hits | hitboxBaritone | cabaletta | Jigsaw | LiquidBounce | Wurst | GishCode | Inertia | Impact | rename_me_please.dll | Future | RusherHack | Pyro | Zamorozka | Konas | WintWare | Nursultan | Norules | Akrien | Sigma | DeadCode | Eternity | WEXSIDE | Rich | RichPremium | EdItMe.dll | mc100.dll | Matix | R3D | Celestial | Wild | Destroy | ArchWare | NightMare | BoberWare | FLauncher | ExLoader | celka | CelestialBaritone | cabaletta | Jigsaw | LiquidBounce | Wurst | GishCode | Inertia | Impact | rename_me_please.dll | Future | RusherHack | Pyro | Zamorozka | Konas | WintWare | Nursultan | Norules | Akrien | Sigma | DeadCode | Eternity | WEXSIDE | Rich | RichPremium | EdItMe.dll | mc100.dll | Matix | R3D | Celestial | Wild Destroy | ArchWare | NightMare | BoberWare | FLauncher | ExLoader | celka | Celestial | xray | x-ray | itemscroller | doomsday | Freecam | MouseTweaks | akrien | AutoChest | ChestStealer | BetterClicker" $downloadDir             = Join-Path $env:TEMP "cheatCheck_tools" $everythingInstaller     = Join-Path $downloadDir "Everything-Setup.exe" $shellbagsPortable       = Join-Path $downloadDir "ShellBagsExplorer.exe" $processHackerInstaller  = Join-Path $downloadDir "ProcessHacker-Setup.exe"
$urls = @{ Everything     = "https://www.voidtools.com/Everything-1.4.1.1024.x64-Setup.exe" ShellBags       = "https://f001.backblazeb2.com/file/EricZimmermanTools/ShellBagsExplorer.exe" ProcessHacker   = "https://wj32.org/processhacker/dl.php?file=processhacker-2.39-setup.exe" }
if (-not (Test-Path $downloadDir)) { New-Item -ItemType Directory -Path $downloadDir -Force | Out-Null }
function Download-File { param( [string]$Url, [string]$OutFile ) Write-Host " Скачиваем   $OutFile ..." -ForegroundColor Cyan try { Invoke-WebRequest -Uri $Url -OutFile $OutFile -UseBasicParsing -ErrorAction Stop Write-Host " Успешно скачано." -ForegroundColor Green } catch { Write-Host "  Ошибка при загрузке: $_" -ForegroundColor Red exit 1 } }
Download-File -Url $urls.Everything     -OutFile $everythingInstaller Download-File -Url $urls.ShellBags       -OutFile $shellbagsPortable Download-File -Url $urls.ProcessHacker   -OutFile $processHackerInstaller
function Install-Silent { param( [string]$Installer, [string]$Args = "/S" ) if (Test-Path $Installer) { Write-Host "Установка $Installer ..." -ForegroundColor Yellow Start-Process -FilePath $Installer -ArgumentList $Args -Wait -ErrorAction Stop Write-Host "  Установка завершена." -ForegroundColor Green } else { Write-Host " Файл инсталлятора не найден: $Installer" -ForegroundColor Red exit 1 } }
Install-Silent -Installer $everythingInstaller Install-Silent -Installer $processHackerInstaller
Write-Host " Запуск ShellBagsExplorer ..." -ForegroundColor Yellow if (Test-Path $shellbagsPortable) { Start-Process -FilePath $shellbagsPortable Write-Host " ShellBagsExplorer запущен." -ForegroundColor Green } else { Write-Host "  Не найден ShellBagsExplorer: $shellbagsPortable" -ForegroundColor Red }
$possiblePaths = @( Join-Path ${env:ProgramFiles} "Everything\Everything.exe", Join-Path ${env:ProgramFiles(x86)} "Everything\Everything.exe" ) $everythingExe = $possiblePaths | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($everythingExe) {    Write-Host "Выполняем поиск в Everything…" -ForegroundColor Cyan    Start-Process -FilePath $everythingExe -ArgumentList @("-search", $SearchTerm) -ErrorAction Stop    Write-Host "Поиск запущен." -ForegroundColor Green} else {    Write-Host "Не удалось найти Everything.exe. Проверьте установку." -ForegroundColor Red    exit 1}
Write-Host "`nВсе операции завершены успешно." -ForegroundColor Green
